themes/next/dist: xenial
language: node_js
node_js:
- node
- 10.15.0
cache: npm
branches:
  only:
  - dev
before_install:
- openssl aes-256-cbc -K $encrypted_2cf61c1c8bc9_key -iv $encrypted_2cf61c1c8bc9_iv
  -in tencent_id_rsa.enc -out ~/.ssh/tencent_id_rsa -d
- chmod 600 ~/.ssh/tencent_id_rsa
- echo -e "Host 132.232.142.219\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- npm install -g hexo-cli
install:
#- cd ./blogs/
#- git clone https://github.com/zjZSTU/hexo-theme-next.git themes/next
- git submodule init
- git submodule update 
- git clone https://github.com/theme-next/theme-next-canvas-nest themes/next/source/lib/canvas-nest
- git clone https://github.com/theme-next/theme-next-algolia-instant-search themes/next/source/lib/algolia-instant-search
- npm install
before_script:
- git config --global user.name $USER_NAME
- git config --global user.email $USER_EMAIL
script:
- pwd
- hexo clean
- hexo generate
- hexo algolia
after_success:
- eval "$(ssh-agent -s)"
- ssh-add ~/.ssh/tencent_id_rsa
# - git clone ubuntu@132.232.142.219:/home/ubuntu/git/zhujian.tech.git upload_git
- mkdir upload_git
- cd upload_git
- git init
# - rm -rf !(.git)
- cp -r ../public/* ./
- git add .
- git commit -m "Update blogs"
- git push --force ubuntu@132.232.142.219:/home/ubuntu/git/zhujian.tech.git master
- cd ..
- sed -i'' "s~https://github.com/zjZSTU/zjzstu.github.com.git~https://${GITHUB_REPO_TOKEN}@github.com/zjZSTU/zjzstu.github.com.git~"
  _config.yml
- sed -i'' "s~git@git.dev.tencent.com:zjZSTU/zjZSTU.coding.me.git~https://zjZSTU:${CODING_REPO_TOKEN}@git.coding.net/zjZSTU/zjZSTU.coding.me.git~"
  _config.yml
- hexo deploy