themes/next/dist: xenial
language: node_js
node_js:
- node
- 10.15.0
cache: npm
branches:
  only:
  - dev
before_install:
- openssl aes-256-cbc -K $encrypted_2cf61c1c8bc9_key -iv $encrypted_2cf61c1c8bc9_iv
  -in tencent_id_rsa.enc -out ~/.ssh/tencent_id_rsa -d
- chmod 600 ~/.ssh/tencent_id_rsa
- echo -e "Host 148.70.133.9\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- npm install -g hexo-cli
install:
- git submodule foreach git pull origin master
- cd ./blogs/
- git clone https://github.com/theme-next/theme-next-canvas-nest themes/next/source/lib/canvas-nest
- git clone https://github.com/theme-next/theme-next-algolia-instant-search themes/next/source/lib/algolia-instant-search
- git clone https://github.com/theme-next/theme-next-fancybox3 themes/next/source/lib/fancybox
- npm install
before_script:
- git config --global user.name $USER_NAME
- git config --global user.email $USER_EMAIL
script:
- pwd
- rm node_modules/kramed/lib/rules/inline.js
- cp inline.js node_modules/kramed/lib/rules/
- npm run gs
- hexo algolia
after_success:
- eval "$(ssh-agent -s)"
- ssh-add ~/.ssh/tencent_id_rsa
# - mkdir upload_git
# - cd upload_git
# - git init
# - cp -r ../public/* ./
# - git add .
# - git commit -m "Update blogs"
# - git push --force git@148.70.133.9:/data/repositories/blogs.git master
# - cd ..
- sed -i'' "s~https://github.com/zjZSTU/zjzstu.github.com.git~https://${GITHUB_REPO_TOKEN}@github.com/zjZSTU/zjzstu.github.com.git~"
  _config.yml
- sed -i'' "s~git@git.dev.tencent.com:zjZSTU/zjZSTU.coding.me.git~https://zjZSTU:${CODING_REPO_TOKEN}@git.coding.net/zjZSTU/zjZSTU.coding.me.git~"
  _config.yml
- hexo deploy